variable "italika_org" {
  default = {
    enable      = true
    description = "italika_lab bootstrap - Organization generated by terraform harness provider"
    projects = {
      "Platform Team AWS-EKS" = {
        enable      = true
        description = "Project generated by terraform harness provider"
      }
      "Platform Team AWS-VMS" = {
        enable      = true
        description = "Project generated by terraform harness provider"
      }
      "Platform Team On-Prem" = {
        enable      = true
        description = "Project generated by terraform harness provider"
      }
    }
  }
}

locals {
  italika_org_delegates = {
    k8s = {
      italika_lab-gke-tf = {
        enable                 = true
        description            = "Delegate deployed and generated by terraform harness provider"
        size                   = "SMALL"
        tags                   = ["gcp-environment"]
        clusterPermissionType  = "CLUSTER_ADMIN"
        customClusterNamespace = "harness-delegate-ng"
        org_id                 = module.bootstrap_italika_org.organization["italika-org"].org_id
      }
    }
  }

  italika_org_connectors = {
    github = {
      italika_platform-dev = {
        enable          = true
        description     = "Github italika_lab - Connector generated by terraform harness provider"
        connection_type = "Account"
        url             = "https://github.com/Crizstian"
        validation_repo = "harness-as-code"
        org_id          = module.bootstrap_italika_org.organization["italika-org"].org_id
        credentials = {
          http = {
            username  = "crizstian"
            token_ref = var.harness_connectors_crizstian_github_token
          }
        }
      }
    }
  }
}
